DoND reraise interupts
qdev-dk/Qcodes pull request #34
Opened 2017-06-01 09:16 UTC by jenshnielsen

so that loops of measurements can be safely stopped

2017-06-01 09:16 UTC, jenshnielsen commented
@WilliamHPNielsen

2017-06-01 11:36 UTC, WilliamHPNielsen requested changes

2017-06-01 11:36 UTC, WilliamHPNielsen commented on qcodes/utils/wrappers.py
>      # try to flush VISA buffers at the beginning of a measurement
It is slightly confusing that `interrupted` is set on the line between the buffer flushing and the comment about buffer flushing.

2017-06-01 11:52 UTC, jenshnielsen commented on qcodes/utils/wrappers.py
>      # try to flush VISA buffers at the beginning of a measurement
Fixed

2017-06-06 12:55 UTC, WilliamHPNielsen approved these changes
That's what the boys want

2017-06-06 12:55 UTC, merged